CREATE TABLE recetas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    codigo VARCHAR(50) NOT NULL,
    descripcion TEXT NOT NULL,
    ingredientes TEXT NOT NULL,
    instrucciones TEXT NOT NULL,
    tiempo VARCHAR(50) NOT NULL,
    dificultad VARCHAR(50) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    porciones INT NOT NULL,
    fecha DATE NOT NULL,
    editado DATE NOT NULL
);

INSERT INTO recetas (id, nombre, codigo, descripcion, ingredientes, instrucciones, tiempo, dificultad, categoria, porciones, fecha, editado) VALUES 
(NULL, 'Tostadas Francesas con Frutas y Miel', 'DY0001', 'Deliciosas tostadas francesas servidas con una mezcla de frutas frescas y un toque de miel.', 'Pan, huevos, leche, frutas mixtas, miel, canela', '1. Batir los huevos con la leche y la canela. 2. Remojar las rebanadas de pan en la mezcla de huevos. 3. Cocinar en una sartén hasta que estén doradas. 4. Servir con frutas y miel por encima.', '15 minutos', 'Fácil', 'Desayuno', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Omelette de Espinacas y Queso de Cabra', 'DY0002', 'Un omelette esponjoso relleno de espinacas frescas y queso de cabra.', 'Huevos, espinacas, queso de cabra, sal, pimienta, aceite de oliva', '1. Batir los huevos con sal y pimienta. 2. Saltear las espinacas en una sartén con aceite de oliva. 3. Verter los huevos batidos sobre las espinacas y cocinar hasta que estén cuajados. 4. Añadir el queso de cabra y doblar el omelette.', '10 minutos', 'Muy fácil', 'Desayuno', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Smoothie de Fresas y Plátano', 'DY0003', 'Un refrescante smoothie hecho con fresas frescas y plátano.', 'Fresas, plátano, yogur, leche, miel', '1. Colocar las fresas, el plátano, el yogur y la leche en una licuadora. 2. Licuar hasta obtener una mezcla suave. 3. Añadir miel al gusto y mezclar nuevamente.', '5 minutos', 'Muy fácil', 'Desayuno', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Avena con Manzana y Canela', 'DY0004', 'Avena cocida con trozos de manzana y un toque de canela.', 'Avena, manzana, leche, agua, canela, azúcar', '1. Cocinar la avena con agua y leche según las instrucciones del paquete. 2. Añadir la manzana picada y la canela durante los últimos minutos de cocción. 3. Endulzar al gusto con azúcar.', '10 minutos', 'Fácil', 'Desayuno', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Panqueques de Avena y Banana', 'DY0005', 'Panqueques saludables hechos con avena y plátano.', 'Avena, plátano, huevos, leche, polvo de hornear, canela', '1. Mezclar la avena, el plátano, los huevos, la leche, el polvo de hornear y la canela en una licuadora. 2. Cocinar en una sartén a fuego medio hasta que estén dorados por ambos lados.', '20 minutos', 'Intermedia', 'Desayuno', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Bagel con Salmón Ahumado y Queso Crema', 'DY0006', 'Un bagel tostado con salmón ahumado y queso crema.', 'Bagel, salmón ahumado, queso crema, cebolla roja, alcaparras, eneldo', '1. Tostar el bagel. 2. Untar el queso crema en cada mitad. 3. Colocar el salmón ahumado encima. 4. Añadir cebolla roja en rodajas, alcaparras y eneldo.', '10 minutos', 'Muy fácil', 'Desayuno', 0, '2024-05-25', '2024-05-25');

INSERT INTO recetas (id, nombre, codigo, descripcion, ingredientes, instrucciones, tiempo, dificultad, categoria, porciones, fecha, editado) VALUES 
(NULL, 'Ensalada de Quinoa con Aguacate y Pollo a la Parrilla', 'AL0001', 'Una ensalada fresca y nutritiva con quinoa, aguacate y pollo a la parrilla.', 'Quinoa, aguacate, pechuga de pollo, espinacas, tomates cherry, limón, aceite de oliva, sal, pimienta', '1. Cocinar la quinoa según las instrucciones del paquete. 2. Asar la pechuga de pollo y cortar en tiras. 3. Mezclar la quinoa, espinacas y tomates cherry en un bol. 4. Añadir el aguacate en cubos y el pollo. 5. Aliñar con jugo de limón, aceite de oliva, sal y pimienta.', '25 minutos', 'Fácil', 'Almuerzo', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Pasta Primavera con Verduras y Salsa de Albahaca', 'AL0002', 'Pasta ligera con una variedad de verduras frescas y una sabrosa salsa de albahaca.', 'Pasta, calabacín, pimientos, tomates cherry, albahaca, ajo, aceite de oliva, sal, pimienta', '1. Cocinar la pasta según las instrucciones del paquete. 2. Saltear el calabacín, los pimientos y los tomates cherry en aceite de oliva. 3. Mezclar la pasta con las verduras y la salsa de albahaca. 4. Servir caliente.', '20 minutos', 'Intermedia', 'Almuerzo', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Sándwich de Pollo a la BBQ con Ensalada de Col', 'AL0003', 'Un sándwich sabroso de pollo a la barbacoa acompañado de una crujiente ensalada de col.', 'Pan de hamburguesa, pechuga de pollo, salsa BBQ, col rallada, zanahoria rallada, mayonesa, vinagre, azúcar, sal, pimienta', '1. Cocinar la pechuga de pollo y mezclar con salsa BBQ. 2. Preparar la ensalada de col mezclando la col y la zanahoria con mayonesa, vinagre, azúcar, sal y pimienta. 3. Montar el sándwich colocando el pollo BBQ y la ensalada de col en el pan de hamburguesa.', '15 minutos', 'Fácil', 'Almuerzo', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Tacos de Pescado con Salsa de Mango', 'AL0004', 'Tacos de pescado fresco con una vibrante salsa de mango.', 'Filetes de pescado, tortillas de maíz, mango, cebolla roja, cilantro, limón, sal, pimienta, aceite de oliva', '1. Cocinar los filetes de pescado en una sartén con aceite de oliva, sal y pimienta. 2. Preparar la salsa de mango mezclando mango picado, cebolla roja, cilantro y jugo de limón. 3. Montar los tacos colocando el pescado y la salsa de mango en las tortillas.', '20 minutos', 'Intermedia', 'Almuerzo', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Bowl de Arroz Integral con Tofu y Vegetales', 'AL0005', 'Un bowl saludable de arroz integral acompañado de tofu y una mezcla de vegetales.', 'Arroz integral, tofu, brócoli, zanahorias, pimientos, salsa de soja, ajo, aceite de sésamo', '1. Cocinar el arroz integral según las instrucciones del paquete. 2. Saltear el tofu en aceite de sésamo hasta que esté dorado. 3. Añadir los vegetales y cocinar hasta que estén tiernos. 4. Mezclar con salsa de soja y servir sobre el arroz.', '30 minutos', 'Intermedia', 'Almuerzo', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Wrap de Pollo con Hummus y Vegetales', 'AL0006', 'Un wrap saludable y lleno de sabor con pollo, hummus y vegetales frescos.', 'Tortillas, pechuga de pollo, hummus, lechuga, tomates, pepino, sal, pimienta', '1. Cocinar la pechuga de pollo y cortar en tiras. 2. Untar hummus en las tortillas. 3. Añadir la lechuga, los tomates, el pepino y el pollo. 4. Enrollar y servir.', '15 minutos', 'Fácil', 'Almuerzo', 0, '2024-05-25', '2024-05-25');

INSERT INTO recetas (id, nombre, codigo, descripcion, ingredientes, instrucciones, tiempo, dificultad, categoria, porciones, fecha, editado) VALUES 
(NULL, 'Salmón al Horno con Miel y Mostaza', 'CN0001', 'Un salmón al horno glaseado con una mezcla de miel y mostaza, jugoso y lleno de sabor.', 'Filetes de salmón, miel, mostaza Dijon, ajo, jugo de limón, sal, pimienta, aceite de oliva', '1. Precalentar el horno a 200°C. 2. Mezclar miel, mostaza, ajo y jugo de limón. 3. Colocar los filetes de salmón en una bandeja para hornear y cubrir con la mezcla de miel y mostaza. 4. Hornear durante 15-20 minutos hasta que el salmón esté cocido.', '25 minutos', 'Fácil', 'Cena', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Pollo en Salsa de Champiñones con Puré de Papas', 'CN0002', 'Pechugas de pollo tiernas en una rica salsa de champiñones, acompañadas de un cremoso puré de papas.', 'Pechugas de pollo, champiñones, cebolla, ajo, crema de leche, caldo de pollo, mantequilla, papas, leche, sal, pimienta', '1. Cocinar las pechugas de pollo en una sartén hasta que estén doradas y reservar. 2. En la misma sartén, saltear cebolla y ajo, luego añadir los champiñones. 3. Añadir la crema de leche y el caldo de pollo, y cocinar hasta que la salsa espese. 4. Regresar el pollo a la sartén y cocinar unos minutos más. 5. Para el puré, hervir las papas hasta que estén tiernas, hacer puré con mantequilla y leche.', '45 minutos', 'Intermedia', 'Cena', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Lasaña de Berenjena y Queso Ricotta', 'CN0003', 'Una lasaña vegetariana con capas de berenjena asada, ricotta y salsa de tomate.', 'Berenjenas, ricotta, mozzarella, salsa de tomate, albahaca, ajo, cebolla, parmesano, sal, pimienta, aceite de oliva', '1. Precalentar el horno a 180°C. 2. Cortar las berenjenas en rodajas y asarlas hasta que estén tiernas. 3. En una sartén, saltear cebolla y ajo, luego añadir la salsa de tomate y albahaca. 4. En una bandeja para hornear, alternar capas de berenjena, ricotta y salsa de tomate. 5. Cubrir con mozzarella y parmesano, y hornear durante 30 minutos.', '1 hora', 'Intermedia', 'Cena', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Estofado de Ternera con Papas y Zanahorias', 'CN0004', 'Un estofado clásico de ternera con papas y zanahorias, cocido a fuego lento hasta que esté tierno y sabroso.', 'Ternera, papas, zanahorias, cebolla, ajo, caldo de carne, vino tinto, tomate, laurel, tomillo, sal, pimienta, aceite de oliva', '1. En una olla grande, dorar la ternera en aceite de oliva y reservar. 2. En la misma olla, saltear cebolla y ajo, luego añadir el vino tinto y reducir. 3. Añadir el caldo de carne, tomate, laurel y tomillo, y regresar la ternera a la olla. 4. Añadir papas y zanahorias, y cocinar a fuego lento durante 2 horas.', '2 horas 30 minutos', 'Difícil', 'Cena', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Risotto de Espárragos y Parmesano', 'CN0005', 'Un risotto cremoso con espárragos frescos y queso parmesano.', 'Arroz arborio, espárragos, cebolla, ajo, caldo de vegetales, vino blanco, parmesano, mantequilla, sal, pimienta, aceite de oliva', '1. En una sartén grande, saltear cebolla y ajo en aceite de oliva. 2. Añadir el arroz y cocinar por un minuto. 3. Añadir el vino blanco y cocinar hasta que se evapore. 4. Añadir el caldo de vegetales poco a poco, removiendo constantemente, hasta que el arroz esté cocido. 5. Añadir los espárragos y cocinar hasta que estén tiernos. 6. Retirar del fuego y añadir parmesano y mantequilla.', '40 minutos', 'Intermedia', 'Cena', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Tacos de Carne Asada con Guacamole', 'CN0006', 'Tacos sabrosos de carne asada servidos con un guacamole casero.', 'Carne de res, tortillas de maíz, aguacates, cebolla, tomate, cilantro, jugo de limón, sal, pimienta, ajo en polvo, comino, aceite de oliva', '1. Marinar la carne con sal, pimienta, ajo en polvo, comino y aceite de oliva, luego asar hasta que esté cocida a su gusto. 2. Cortar la carne en tiras finas. 3. Preparar el guacamole machacando los aguacates y mezclando con cebolla picada, tomate, cilantro y jugo de limón. 4. Calentar las tortillas y servir la carne con guacamole.', '30 minutos', 'Fácil', 'Cena', 0, '2024-05-25', '2024-05-25');

INSERT INTO recetas (id, nombre, codigo, descripcion, ingredientes, instrucciones, tiempo, dificultad, categoria, porciones, fecha, editado) VALUES 
(NULL, 'Ensalada Caprese', 'VE0001', 'Una ensalada clásica italiana con tomates frescos, mozzarella y albahaca.', 'Tomates, mozzarella fresca, albahaca, aceite de oliva, sal, pimienta', '1. Cortar los tomates y la mozzarella en rodajas. 2. Alternar las rodajas de tomate y mozzarella en un plato. 3. Añadir hojas de albahaca. 4. Aliñar con aceite de oliva, sal y pimienta.', '10 minutos', 'Muy fácil', 'Vegetariano', 2, '2024-05-25', '2024-05-25'),
(NULL, 'Pizza Margarita', 'VE0002', 'Una pizza simple y deliciosa con tomate, mozzarella y albahaca.', 'Masa de pizza, salsa de tomate, mozzarella, albahaca, aceite de oliva, sal', '1. Precalentar el horno a 220°C. 2. Extender la masa de pizza y cubrir con salsa de tomate. 3. Añadir mozzarella y albahaca. 4. Hornear durante 15 minutos hasta que el queso esté derretido y la masa dorada.', '20 minutos', 'Fácil', 'Vegetariano', 2, '2024-05-25', '2024-05-25'),
(NULL, 'Curry de Garbanzos y Espinacas', 'VE0003', 'Un curry saludable y nutritivo con garbanzos y espinacas.', 'Garbanzos, espinacas, cebolla, ajo, jengibre, leche de coco, curry en polvo, aceite de oliva, sal, pimienta', '1. Calentar el aceite en una sartén y saltear la cebolla, ajo y jengibre. 2. Añadir el curry en polvo y cocinar por un minuto. 3. Añadir los garbanzos y la leche de coco, cocinar a fuego lento por 10 minutos. 4. Añadir las espinacas y cocinar hasta que estén tiernas.', '30 minutos', 'Intermedia', 'Vegetariano', 4, '2024-05-25', '2024-05-25'),
(NULL, 'Lasaña de Vegetales', 'VE0004', 'Lasaña con una mezcla de vegetales y ricotta.', 'Láminas de lasaña, berenjena, calabacín, espinacas, ricotta, mozzarella, salsa de tomate, albahaca, sal, pimienta', '1. Precalentar el horno a 180°C. 2. Asar las berenjenas y calabacines en rodajas. 3. Montar la lasaña alternando láminas de lasaña, vegetales, ricotta y salsa de tomate. 4. Cubrir con mozzarella y hornear durante 30 minutos.', '1 hora', 'Intermedia', 'Vegetariano', 6, '2024-05-25', '2024-05-25'),
(NULL, 'Falafel con Salsa de Yogur', 'VE0005', 'Deliciosos falafels servidos con una salsa fresca de yogur.', 'Garbanzos, cebolla, ajo, perejil, cilantro, comino, harina de garbanzo, sal, pimienta, aceite de oliva, yogur, limón, menta', '1. Mezclar los garbanzos con cebolla, ajo, perejil, cilantro, comino, sal y pimienta en un procesador de alimentos. 2. Formar bolitas y freír en aceite de oliva. 3. Mezclar yogur con jugo de limón y menta para la salsa. 4. Servir los falafels con la salsa de yogur.', '45 minutos', 'Intermedia', 'Vegetariano', 4, '2024-05-25', '2024-05-25'),
(NULL, 'Tarta de Espinacas y Queso Feta', 'VE0006', 'Tarta salada con espinacas y queso feta, ideal para cualquier comida.', 'Masa quebrada, espinacas, queso feta, huevos, cebolla, ajo, crema de leche, sal, pimienta', '1. Precalentar el horno a 180°C. 2. Saltear la cebolla y el ajo, añadir las espinacas hasta que estén tiernas. 3. Mezclar las espinacas con queso feta, huevos y crema de leche. 4. Verter la mezcla en la masa quebrada y hornear durante 35-40 minutos.', '50 minutos', 'Intermedia', 'Vegetariano', 6, '2024-05-25', '2024-05-25');

INSERT INTO recetas (id, nombre, codigo, descripcion, ingredientes, instrucciones, tiempo, dificultad, categoria, porciones, fecha, editado) VALUES 
(NULL, 'Tofu Salteado con Verduras', 'VG0001', 'Tofu salteado con una mezcla de verduras frescas.', 'Tofu firme, brócoli, zanahorias, pimientos, salsa de soja, aceite de sésamo, ajo, jengibre', '1. Cortar el tofu en cubos y saltear en aceite de sésamo hasta que esté dorado. 2. Añadir ajo y jengibre picados, luego las verduras. 3. Añadir salsa de soja y cocinar hasta que las verduras estén tiernas.', '20 minutos', 'Fácil', 'Vegano', 2, '2024-05-25', '2024-05-25'),
(NULL, 'Ensalada de Lentejas con Vinagreta de Mostaza', 'VG0002', 'Ensalada nutritiva de lentejas con una vinagreta de mostaza.', 'Lentejas cocidas, tomates cherry, pepino, cebolla roja, perejil, mostaza Dijon, vinagre de manzana, aceite de oliva, sal, pimienta', '1. Mezclar las lentejas con tomates cherry, pepino y cebolla roja. 2. Preparar la vinagreta mezclando mostaza, vinagre, aceite, sal y pimienta. 3. Aliñar la ensalada con la vinagreta.', '15 minutos', 'Muy fácil', 'Vegano', 2, '2024-05-25', '2024-05-25'),
(NULL, 'Sopa de Tomate y Albahaca', 'VG0003', 'Sopa reconfortante de tomate con un toque de albahaca.', 'Tomates, cebolla, ajo, caldo de vegetales, albahaca, aceite de oliva, sal, pimienta', '1. Saltear cebolla y ajo en aceite de oliva. 2. Añadir los tomates picados y el caldo de vegetales, cocinar por 20 minutos. 3. Añadir albahaca y cocinar 5 minutos más. 4. Licuar la sopa hasta obtener una textura suave.', '30 minutos', 'Fácil', 'Vegano', 4, '2024-05-25', '2024-05-25'),
(NULL, 'Burritos de Frijoles Negros y Arroz', 'VG0004', 'Burritos veganos rellenos de frijoles negros, arroz y verduras.', 'Tortillas de trigo, frijoles negros, arroz, pimientos, cebolla, ajo, comino, aguacate, cilantro, sal, pimienta', '1. Saltear cebolla, ajo y pimientos en aceite de oliva. 2. Añadir los frijoles negros y el arroz cocido, sazonar con comino, sal y pimienta. 3. Rellenar las tortillas con la mezcla de frijoles y arroz, y añadir aguacate y cilantro picado.', '25 minutos', 'Intermedia', 'Vegano', 4, '2024-05-25', '2024-05-25'),
(NULL, 'Hamburguesa de Garbanzos', 'VG0005', 'Hamburguesa vegana de garbanzos servida en pan integral.', 'Garbanzos, avena, cebolla, ajo, comino, pimentón, pan integral, lechuga, tomate, aguacate', '1. Triturar los garbanzos y mezclar con avena, cebolla, ajo, comino y pimentón. 2. Formar hamburguesas y cocinarlas en una sartén con aceite de oliva. 3. Servir en pan integral con lechuga, tomate y aguacate.', '30 minutos', 'Intermedia', 'Vegano', 4, '2024-05-25', '2024-05-25'),
(NULL, 'Tarta de Chocolate Vegana', 'VG0006', 'Deliciosa tarta de chocolate sin ingredientes de origen animal.', 'Harina de trigo, cacao en polvo, azúcar de coco, leche de almendra, aceite de coco, bicarbonato de sodio, vinagre de manzana', '1. Precalentar el horno a 180°C. 2. Mezclar los ingredientes secos en un bol. 3. Añadir los ingredientes líquidos y mezclar bien. 4. Verter la mezcla en un molde y hornear durante 30-35 minutos.', '45 minutos', 'Intermedia', 'Vegano', 8, '2024-05-25', '2024-05-25');

INSERT INTO recetas (id, nombre, codigo, descripcion, ingredientes, instrucciones, tiempo, dificultad, categoria, porciones, fecha, editado) VALUES 
(NULL, 'Panqueques de Plátano sin Gluten', 'SG0001', 'Deliciosos panqueques sin gluten a base de plátano.', 'Plátanos maduros, huevos, harina de almendra, canela, polvo de hornear, aceite de coco', '1. Machacar los plátanos en un bol. 2. Añadir los huevos y mezclar bien. 3. Incorporar la harina de almendra, canela y polvo de hornear. 4. Cocinar en una sartén con aceite de coco hasta que estén dorados por ambos lados.', '15 minutos', 'Fácil', 'Sin Gluten', 2, '2024-05-25', '2024-05-25'),
(NULL, 'Ensalada de Quinua y Verduras', 'SG0002', 'Ensalada fresca de quinua con una variedad de verduras.', 'Quinua, pepino, tomates cherry, cebolla roja, perejil, jugo de limón, aceite de oliva, sal, pimienta', '1. Cocinar la quinua según las instrucciones del paquete. 2. Mezclar la quinua cocida con las verduras picadas. 3. Aliñar con jugo de limón, aceite de oliva, sal y pimienta.', '20 minutos', 'Muy fácil', 'Sin Gluten', 2, '2024-05-25', '2024-05-25'),
(NULL, 'Pollo al Limón con Hierbas', 'SG0003', 'Pechugas de pollo marinadas en limón y hierbas, cocidas a la parrilla.', 'Pechugas de pollo, jugo de limón, ajo, tomillo, romero, aceite de oliva, sal, pimienta', '1. Marinar las pechugas de pollo con jugo de limón, ajo, tomillo, romero, sal y pimienta. 2. Cocinar a la parrilla hasta que estén doradas y cocidas.', '30 minutos', 'Fácil', 'Sin Gluten', 2, '2024-05-25', '2024-05-25'),
(NULL, 'Sopa de Calabaza', 'SG0004', 'Sopa cremosa de calabaza, perfecta para los días fríos.', 'Calabaza, cebolla, ajo, caldo de vegetales, leche de coco, nuez moscada, sal, pimienta', '1. Saltear la cebolla y el ajo en una olla grande. 2. Añadir la calabaza y el caldo de vegetales, cocinar hasta que la calabaza esté tierna. 3. Añadir la leche de coco y nuez moscada, y licuar hasta obtener una textura suave.', '40 minutos', 'Fácil', 'Sin Gluten', 4, '2024-05-25', '2024-05-25'),
(NULL, 'Pizza sin Gluten', 'SG0005', 'Pizza con masa sin gluten cubierta con tus ingredientes favoritos.', 'Harina sin gluten, levadura, agua, sal, aceite de oliva, salsa de tomate, mozzarella, albahaca', '1. Precalentar el horno a 220°C. 2. Preparar la masa mezclando la harina sin gluten con levadura, agua, sal y aceite de oliva. 3. Dejar reposar la masa durante 30 minutos. 4. Extender la masa y cubrir con salsa de tomate, mozzarella y albahaca. 5. Hornear durante 15-20 minutos.', '1 hora', 'Intermedia', 'Sin Gluten', 2, '2024-05-25', '2024-05-25'),
(NULL, 'Brownies sin Gluten', 'SG0006', 'Deliciosos brownies de chocolate sin gluten.', 'Harina de almendra, cacao en polvo, azúcar de coco, huevos, aceite de coco, extracto de vainilla, sal', '1. Precalentar el horno a 180°C. 2. Mezclar los ingredientes secos en un bol. 3. Añadir los ingredientes líquidos y mezclar bien. 4. Verter la mezcla en un molde y hornear durante 20-25 minutos.', '35 minutos', 'Intermedia', 'Sin Gluten', 8, '2024-05-25', '2024-05-25');

INSERT INTO recetas (id, nombre, codigo, descripcion, ingredientes, instrucciones, tiempo, dificultad, categoria, porciones, fecha, editado) VALUES 
(NULL, 'Tarta de Limón con Merengue', 'PS0001', 'Una deliciosa tarta de limón cubierta con un suave merengue.', 'Harina, mantequilla, azúcar, huevos, limones, leche condensada, sal, agua, azúcar glas', '1. Preparar la base mezclando harina, mantequilla, azúcar y sal. 2. Hornear la base hasta que esté dorada. 3. Mezclar leche condensada, jugo de limón y yemas de huevo para el relleno. 4. Verter el relleno sobre la base y hornear. 5. Batir claras de huevo con azúcar glas para el merengue. 6. Cubrir la tarta con el merengue y dorar en el horno.', '1 hora', 'Intermedia', 'Postre', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Brownies de Chocolate con Nueces', 'PS0002', 'Brownies ricos y húmedos con trozos de nueces.', 'Chocolate, mantequilla, azúcar, huevos, harina, nueces, polvo de hornear, sal', '1. Derretir el chocolate y la mantequilla juntos. 2. Batir los huevos con el azúcar y añadir la mezcla de chocolate. 3. Incorporar la harina, el polvo de hornear y la sal. 4. Añadir las nueces picadas. 5. Verter en un molde y hornear hasta que estén cocidos.', '45 minutos', 'Intermedia', 'Postre', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Cheesecake de Frutos Rojos', 'PS0003', 'Un suave cheesecake con una cobertura de frutos rojos.', 'Galletas, mantequilla, queso crema, azúcar, huevos, vainilla, frutos rojos, gelatina', '1. Triturar las galletas y mezclar con mantequilla derretida para la base. 2. Hornear la base hasta que esté dorada. 3. Mezclar queso crema, azúcar, huevos y vainilla para el relleno. 4. Verter el relleno sobre la base y hornear. 5. Preparar una gelatina con los frutos rojos y verter sobre el cheesecake enfriado.', '1 hora 30 minutos', 'Difícil', 'Postre', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Flan de Caramelo', 'PS0004', 'Un flan cremoso con una capa de caramelo.', 'Leche, azúcar, huevos, vainilla, agua', '1. Hacer un caramelo con azúcar y agua y verter en moldes. 2. Mezclar leche, huevos y vainilla. 3. Verter la mezcla en los moldes sobre el caramelo. 4. Hornear al baño maría hasta que esté cuajado.', '1 hora', 'Intermedia', 'Postre', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Galletas de Avena y Pasas', 'PS0005', 'Galletas crujientes y saludables con avena y pasas.', 'Avena, harina, azúcar, mantequilla, huevos, pasas, bicarbonato de sodio, canela, sal', '1. Batir la mantequilla con el azúcar y los huevos. 2. Añadir harina, avena, bicarbonato, canela y sal. 3. Incorporar las pasas. 4. Formar bolitas y colocar en una bandeja para hornear. 5. Hornear hasta que estén doradas.', '30 minutos', 'Fácil', 'Postre', 0, '2024-05-25', '2024-05-25'),
(NULL, 'Mousse de Chocolate con Crema Batida', 'PS0006', 'Un mousse suave y aireado de chocolate con crema batida.', 'Chocolate, huevos, azúcar, crema para batir, vainilla, sal', '1. Derretir el chocolate y dejar enfriar un poco. 2. Batir las yemas de huevo con azúcar y añadir el chocolate. 3. Batir las claras de huevo con sal hasta obtener picos firmes e incorporar a la mezcla de chocolate. 4. Batir la crema con vainilla hasta obtener picos suaves y añadir a la mezcla. 5. Refrigerar por al menos 2 horas antes de servir.', '2 horas 30 minutos', 'Intermedia', 'Postre', 0, '2024-05-25', '2024-05-25');

INSERT INTO recetas (id, nombre, codigo, descripcion, ingredientes, instrucciones, tiempo, dificultad, categoria, porciones, fecha, editado) VALUES 
(NULL, 'Tarta de Manzana Sin Azúcar', 'SA0001', 'Una tarta de manzana deliciosa y saludable sin azúcar añadido.', 'Manzanas, harina integral, avena, canela, nuez moscada, mantequilla sin sal, extracto de vainilla', '1. Precalentar el horno a 180°C. 2. Pelar y cortar las manzanas. 3. Mezclar harina, avena, canela y nuez moscada. 4. Añadir mantequilla y extracto de vainilla, mezclar bien. 5. Colocar las manzanas en una fuente para horno y cubrir con la mezcla. 6. Hornear durante 45 minutos.', '1 hora', 'Intermedia', 'Sin Azúcar', 8, '2024-05-25', '2024-05-25'),
(NULL, 'Brownies de Batata Sin Azúcar', 'SA0002', 'Brownies hechos con batata para un toque dulce sin azúcar.', 'Batata cocida, cacao en polvo, harina de almendra, huevos, aceite de coco, extracto de vainilla, sal', '1. Precalentar el horno a 180°C. 2. Mezclar la batata cocida con cacao en polvo, harina de almendra, huevos, aceite de coco, extracto de vainilla y sal. 3. Verter la mezcla en un molde y hornear durante 25 minutos.', '35 minutos', 'Fácil', 'Sin Azúcar', 8, '2024-05-25', '2024-05-25'),
(NULL, 'Helado de Plátano y Fresas Sin Azúcar', 'SA0003', 'Un helado cremoso y saludable hecho solo con plátanos y fresas.', 'Plátanos maduros, fresas', '1. Cortar los plátanos y las fresas en rodajas y congelar durante 2 horas. 2. Licuar los plátanos y las fresas congeladas hasta obtener una mezcla cremosa. 3. Servir inmediatamente o congelar por 1 hora para una textura más firme.', '2 horas 15 minutos', 'Muy fácil', 'Sin Azúcar', 4, '2024-05-25', '2024-05-25'),
(NULL, 'Pudín de Chía y Vainilla Sin Azúcar', 'SA0004', 'Un pudín nutritivo de semillas de chía con sabor a vainilla, sin azúcar añadido.', 'Leche de almendra, semillas de chía, extracto de vainilla, canela', '1. Mezclar la leche de almendra con las semillas de chía, el extracto de vainilla y la canela. 2. Dejar reposar en el refrigerador durante al menos 4 horas o toda la noche. 3. Servir frío.', '4 horas', 'Muy fácil', 'Sin Azúcar', 4, '2024-05-25', '2024-05-25'),
(NULL, 'Pastel de Zanahoria Sin Azúcar', 'SA0005', 'Un delicioso pastel de zanahoria sin azúcar añadido.', 'Zanahorias ralladas, harina de almendra, huevos, aceite de coco, canela, nuez moscada, polvo de hornear, extracto de vainilla', '1. Precalentar el horno a 180°C. 2. Mezclar las zanahorias ralladas con harina de almendra, huevos, aceite de coco, canela, nuez moscada, polvo de hornear y extracto de vainilla. 3. Verter la mezcla en un molde y hornear durante 35-40 minutos.', '50 minutos', 'Intermedia', 'Sin Azúcar', 8, '2024-05-25', '2024-05-25'),
(NULL, 'Muffins de Arándanos Sin Azúcar', 'SA0006', 'Muffins suaves y esponjosos de arándanos sin azúcar añadido.', 'Harina de almendra, harina de coco, huevos, leche de almendra, aceite de coco, arándanos, polvo de hornear, extracto de vainilla', '1. Precalentar el horno a 180°C. 2. Mezclar la harina de almendra, harina de coco, huevos, leche de almendra, aceite de coco, arándanos, polvo de hornear y extracto de vainilla. 3. Verter la mezcla en moldes para muffins y hornear durante 20-25 minutos.', '35 minutos', 'Fácil', 'Sin Azúcar', 12, '2024-05-25', '2024-05-25');
